### ISSUE TITLE
Multiple Accounts at once?

### ISSUE THREAD

**Issue by GHST-13** [razewerz/Instagram-accounts-creator#3]
I'm attempting to create IG accounts at mass scale but unsure how to do so. 
How should i go about creating multiple accounts?

Kind of leaving it on for infinity (granted i have enough proxies)
Also creating a data base that stores all the usernames and passwords without having to scroll through CMD and grabbing them all would be nice

**Comment by GHST-13** [comment]
Also, how do I load up proxies? The directions are very vague and I don't really know much about coding, my apologies in advance.

**Comment by razewerz** [comment]
If i don't think so , you are trying to create IGS with the profile pictures , so you can automate it when the creation happens. and for storing the information in like an txt file absolutely can be.

**Comment by razewerz** [comment]
For proxies you can program an automation , for example select the proxy and change it in “X" minutes  and the “X” = the time of “Y” IGS created.
