### ISSUE TITLE
mail check unresolved

### ISSUE THREAD

**Issue by Goli777** [razewerz/Instagram-accounts-creator#4]
Not resolved email verification
no email in fakebox
Help please

**Comment by razewerz** [comment]
The problem specifically comes from the fake emails provider.
I'll use another service soon.

**Comment by razewerz** [comment]
well I've updated the repo, everthing works fine.
Thanks for your notice.

**Comment by Goli777** [comment]
I did my own fake email provider with API
but don't know how to implement it in a script
